# Извлечено из web-клиента zvuk.com v8.6.2
query getPlaylistsShortInfo($ids: [ID!]!, $withTracks: Boolean = false) {
  playlists(ids: $ids) {
    id
    title
    tracks(limit: 10, offset: 0) @include(if: $withTracks) {
      ...PlayerTrackData
    }
    allTracks: tracks(limit: 200, offset: 0) @include(if: $withTracks) {
      id
    }
    image {
      src
    }
    trackCount
    profile {
      id
      name
      image {
        src
      }
    }
    childParam
    isPublic
    duration
  }
}

fragment PlayerTrackData on Track {
  id
  title
  lyrics
  hasFlac
  duration
  explicit
  availability
  artistTemplate
  childParam
  mark
  artists {
    id
    title
    image {
      src
      palette
    }
    mark
  }
  release {
    id
    title
    image {
      src
      palette
    }
  }
  zchan
  __typename
}
